#STUDENT TABLE
INSERT INTO STUDENT
VALUES (100000001, 'JOHN', 'DOE', 'JDOE@UWINDSOR.CA', 'COMPUTER SCIENCE', 90.4, 'CS');
INSERT INTO STUDENT
VALUES (100000002, 'AARON', 'WILLIAMS', 'AWILLIAMS@UWINDSOR.CA', 'COMPUTER SCIENCE', 82.3, 'CS');
INSERT INTO STUDENT
VALUES (100000003, 'CHRISTIAN', 'DEFOE', 'CDEFOE@UWINDSOR.CA', 'COMPUTER SCIENCE', 77.9, 'CS');
INSERT INTO STUDENT
VALUES (100000004, 'CAROLYN', 'JONES', 'CJONES@UWINDSOR.CA', 'COMPUTER SCIENCE', 68.6, 'CS');
INSERT INTO STUDENT
VALUES (100000005, 'ZACK', 'MILLER', 'ZMILLER@UWINDSOR.CA', 'COMPUTER SCIENCE', 63.1, 'CS');
INSERT INTO STUDENT
VALUES (100000006, 'TAYLOR', 'SCOTT', 'TSCOTT@UWINDSOR.CA', 'CHEMISTRY', 92.0, 'CH');
INSERT INTO STUDENT
VALUES (100000007, 'JARED', 'COOK', 'JCOOK@UWINDSOR.CA', 'CHEMISTRY', 87.5, 'CH');
INSERT INTO STUDENT
VALUES (100000008, 'BAILEY', 'MURPHY', 'BMURPHY@UWINDSOR.CA', 'CHEMISTRY', 75.8, 'CH');
INSERT INTO STUDENT
VALUES (100000009, 'ADAM', 'GREEN', 'AGREEN@UWINDSOR.CA', 'CHEMISTRY', 66.2, 'CH');
INSERT INTO STUDENT
VALUES (101000000, 'ROSS', 'MORRIS', 'RMORRIS@UWINDSOR.CA', 'CHEMISTRY', 58.7, 'CH');
COMMIT;

#PROFESSOR TABLE
INSERT INTO PROFESSOR
VALUES (9001, 'BOBBY', 'JEAN', 'BJEAN@UWINDSOR.CA', 'CS');
INSERT INTO PROFESSOR
VALUES (9002, 'CLAIRE', 'BAKER', 'CBAKER@UWINDSOR.CA', 'CS');
INSERT INTO PROFESSOR
VALUES (9003, 'HAROLD', 'BEAUMONT', 'HBEAUMONT@UWINDSOR.CA', 'CH');
INSERT INTO PROFESSOR
VALUES (9004, 'KATIE', 'SMITH', 'KSMITH@UWINDSOR.CA', 'CH');
INSERT INTO PROFESSOR
VALUES (9005, 'BRANDON', 'BROWN', 'BBROWN@UWINDSOR.CA', 'BU');
INSERT INTO PROFESSOR
VALUES (9006, 'WILLIAM', 'DAVIS', 'WDAVIS@UWINDSOR.CA', 'EN');
COMMIT;

#COURSE TABLE
INSERT INTO COURSE
VALUES ('COMP1050', 'INTRO TO PROGRAMMING', 'DESCRIPTION OF COMP1050', 'CS');
INSERT INTO COURSE
VALUES ('COMP2080', 'OOP USING JAVA', 'DESCRIPTION OF COMP2080', 'CS');
INSERT INTO COURSE
VALUES ('COMP2260', 'DATABASE MANAGEMENT SYSTEMS', 'DESCRIPTION OF COMP2260', 'CS');
INSERT INTO COURSE
VALUES ('CHEM3470', 'SPECTROSCOPIC STRUCTURE IDENTIFICATION', 'DESCRIPTION OF CHEM3470', 'CH');
INSERT INTO COURSE
VALUES ('CHEM3801', 'PRINCIPLES OF INSTRUMENTAL ANALYSIS', 'DESCRIPTION OF CHEM3810', 'CH');
INSERT INTO COURSE
VALUES ('CHEM4540', 'BIO AND SUSTAINABLE MATERIALS', 'DESCRIPTION OF CHEM4540', 'CH');
INSERT INTO COURSE
VALUES ('BUSS4540', 'BUSINESS MANAGEMENT', 'DESCRIPTION OF BUSS4540', 'BU');
INSERT INTO COURSE
VALUES ('BUSS2500', 'ECONOMICS I', 'DESCRIPTION OF BUSS2500', 'BU');
INSERT INTO COURSE
VALUES ('BUSS1000', 'ECONOMICS II', 'DESCRIPTION OF BUSS1000', 'BU');
INSERT INTO COURSE
VALUES ('ENGI4540', 'MECHANICS I', 'DESCRIPTION OF ENGI4540', 'EN');
INSERT INTO COURSE
VALUES ('ENGI3540', 'MECHANICS II', 'DESCRIPTION OF ENGI3540', 'EN');
INSERT INTO COURSE
VALUES ('ENGI1000', 'ENGINEERING PRINCIPLES', 'DESCRIPTION OF ENGI1000', 'EN');


#DEPARTMENT TABLE
INSERT INTO DEPARTMENT
VALUES ('CS', 'COMPUTER SCIENCE');
INSERT INTO DEPARTMENT
VALUES ('CH', 'CHEMISTRY');
COMMIT;

#ROOM TABLE
INSERT INTO ROOM
VALUES (101, 'ERIE HALL', 110);
INSERT INTO ROOM
VALUES (102, 'ERIE HALL', 60);
INSERT INTO ROOM
VALUES (103, 'ERIE HALL', 35);
INSERT INTO ROOM
VALUES (201, 'ESSEX HALL', 105);
INSERT INTO ROOM
VALUES (202, 'ESSEX HALL', 55);
INSERT INTO ROOM
VALUES (203, 'ESSEX HALL', 30);
COMMIT;

#STUDENT_RECORDS TABLE
INSERT INTO STUDENT_RECORDS
VALUES (1111, 100000001, '1234', 82, 'PASS', 2018, 'F');
COMMIT;

#SECTION_RECORS TABLE
INSERT INTO SECTION_RECORS
VALUES (01, '1234', 'COMP1050', 9001, 101, 'Wednesday', '3:00pm', '6:00pm');
COMMIT;